const enum COLOR_PALETTE {
  AIGLE_BLUE = '#2688f0',
  AIGLE_BLACK = '#0d0d0d',
  AIGLE_WHITE = '#fffffe',
  AIGLE_LIGHT_BLUE = '#56a2f3',
  AIGLE_DARK_BLUE = '#0f6fd4',
  AIGLE_LIGHT_BLACK = '#262626',
  AIGLE_GREY = '#F8F8FA',

  AIGLE_RED = '#f5222d',
  AIGLE_GREEN = '#3CB346',
  AIGLE_YELLOW = '#FC8801',

  /** Input */
  AIGLE_INPUT_BACKGROUND = '#F4F5F5',
  AIGLE_INPUT_PLACEHOLDER_COLOR = '#6E7174',
  AIGLE_INPUT_HOVER_BG = '#ECECED',

  /** Header searchTool */
  AIGLE_HEADER_SEARCH_BG = '#E5E8EA',
  AIGLE_HEADER_SEARCH_BG_HOVER = '#C6CACD',

  /** menu selected */
  AIGLE_MENU_SELECTED_BG = '#F0FAFF',
}

export { COLOR_PALETTE };
